version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    # command: bash -c "source /root/miniconda3/etc/profile.d/conda.sh && conda activate unsloth_env && python3 main.py"
    
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]